# Generated by Django 5.2.5 on 2025-08-07 22:49

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uuid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789x', editable=False, length=8, max_length=8, prefix='', unique=True),
        ),
    ]
