# Generated by Django 5.2.5 on 2025-08-07 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_customuser_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uuid',
            new_name='user_uuid',
        ),
    ]
