# Generated by Django 5.2.5 on 2025-08-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_rename_uuid_customuser_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
