# Generated by Django 5.2.5 on 2025-09-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_benefits_product_caution_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_stock',
            field=models.BooleanField(default=False),
        ),
    ]
