# Generated by Django 5.2.5 on 2025-09-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_benefits_alter_product_caution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='product',
            name='caution',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='product',
            name='key_ingredients',
        ),
        migrations.RemoveField(
            model_name='product',
            name='side_effects',
        ),
        migrations.RemoveField(
            model_name='product',
            name='suitable_for',
        ),
        migrations.CreateModel(
            name='ProductBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCaution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cautions', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDosage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosage', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductKeyIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_ingredients', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effects', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSuitableFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suitable_for', to='products.product')),
            ],
        ),
    ]
