# Generated by Django 5.2.5 on 2025-09-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('cover', 'Cover'), ('square', 'Square'), ('thumbnail', 'Thumbnail'), ('zoom', 'Zoom'), ('gallery', 'Gallery'), ('banner', 'Banner')], default='gallery', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_stock',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
