# Generated by Django 5.2.5 on 2025-09-17 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_is_available_productimage_image_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
