# Generated by Django 5.2.5 on 2025-11-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_product_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prescription_required',
            field=models.BooleanField(default=False),
        ),
    ]
